version: '3.8'

services:
  backend:
    build: .
    container_name: cpen321-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - DB_URI=${DB_URI}
    volumes:
      # Mount uploads directory to persist uploaded files
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/hobbies', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  uploads:
    driver: local
